# Model Training

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
df = pd.read_csv('./data/gemstone.csv')

In [2]:
df.head()

id  carat        cut color clarity  depth  table     x     y     z  price
0   0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [3]:
df=df.drop(labels=['id'],axis=1)

In [4]:
df.head()

carat        cut color clarity  depth  table     x     y     z  price
0   1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55  13619
1   2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05  13387
2   0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50   2772
3   0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71    666
4   1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77  14453

In [5]:
# Independent and dependent features
X=df.drop(labels=['price'], axis=1)
Y=df[['price']]

In [6]:
X

carat        cut color clarity  depth  table     x     y     z
0        1.52    Premium     F     VS2   62.2   58.0  7.27  7.33  4.55
1        2.03  Very Good     J     SI2   62.0   58.0  8.06  8.12  5.05
2        0.70      Ideal     G     VS1   61.2   57.0  5.69  5.73  3.50
3        0.32      Ideal     G     VS1   61.6   56.0  4.38  4.41  2.71
4        1.70    Premium     G     VS2   62.6   59.0  7.65  7.61  4.77
...       ...        ...   ...     ...    ...    ...   ...   ...   ...
193568   0.31      Ideal     D    VVS2   61.1   56.0  4.35  4.39  2.67
193569   0.70    Premium     G    VVS2   60.3   58.0  5.75  5.77  3.47
193570   0.73  Very Good     F     SI1   63.1   57.0  5.72  5.75  3.62
193571   0.34  Very Good     D     SI1   62.9   55.0  4.45  4.49  2.81
193572   0.71       Good     E     SI2   60.8   64.0  5.73  5.71  3.48

[193573 rows x 9 columns]

In [7]:
Y

price
0       13619
1       13387
2        2772
3         666
4       14453
...       ...
193568   1130
193569   2874
193570   3036
193571    681
193572   2258

[193573 rows x 1 columns]

In [11]:
# Define which column should be ordinal-encoded and which should be scaled
categorical_cols = X.select_dtypes(include='object').columns
numerical_cols = X.select_dtypes(exclude='object').columns

In [12]:
categorical_cols

Index(['cut', 'color', 'clarity'], dtype='object')

In [13]:
numerical_cols

Index(['carat', 'depth', 'table', 'x', 'y', 'z'], dtype='object')

In [14]:
# Define the custom ranking for each ordinal variable
cut_categories = ['Fair', 'Good', 'Very Good', 'Premium', 'Ideal']
color_categories = ['D', 'E', 'F', 'G', 'H', 'I', 'J']
clarity_categories = ['I1', 'SI2', 'SI1', 'VS2', 'VS1', 'VVS2', 'VVS1', 'IF']

In [15]:
from sklearn.impute import SimpleImputer # for handling missing values
from sklearn.preprocessing import StandardScaler # for handling feature scaling
from sklearn.preprocessing import OrdinalEncoder #For Ordinal encoding
## Pipelines
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

In [16]:
## Numerical Pipeline
num_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='median')),
    ('scaler',StandardScaler())
    ]
)

##Categorical Pipeline

cat_pipeline=Pipeline(
    steps=[
    ('imputer',SimpleImputer(strategy='most_frequent')),
    ('ordinalencoder',OrdinalEncoder(categories=[cut_categories, color_categories, clarity_categories])),
    ('scaler',StandardScaler())
    ]
)

preprocessor=ColumnTransformer([
('num_pipeline',num_pipeline,numerical_cols),
('cat_pipeline',cat_pipeline,categorical_cols)
])

In [17]:
#Train Test split
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.30,random_state=30)

In [18]:
X_train

carat      cut color clarity  depth  table     x     y     z
168192   0.34    Ideal     I    VVS2   60.9   57.0  4.56  4.53  2.76
35202    0.90     Good     E     SI1   63.8   57.0  6.07  6.03  3.87
41091    1.02  Premium     G     VS1   62.7   58.0  6.35  6.39  4.00
31239    0.32  Premium     G     VS2   62.1   59.0  4.37  4.35  2.71
45722    0.35    Ideal     J    VVS2   61.1   56.0  4.53  4.57  2.78
...       ...      ...   ...     ...    ...    ...   ...   ...   ...
66455    0.31    Ideal     E     SI1   61.8   56.0  4.31  4.35  2.68
46220    1.25    Ideal     G     SI2   62.0   56.0  6.88  6.95  4.28
98804    1.00     Good     G     SI1   63.5   56.0  6.29  6.37  4.02
48045    1.10    Ideal     G     VS1   59.9   60.0  6.68  6.77  4.01
169765   0.91    Ideal     G     SI1   62.7   57.0  6.14  6.18  3.86

[135501 rows x 9 columns]

In [19]:
preprocessor.fit_transform(X_train)

array([[-0.97543926, -0.84960654, -0.12153081, ...,  0.87407553,
         1.52872212,  1.35273128],
       [ 0.2351953 ,  1.83363716, -0.12153081, ..., -2.14455824,
        -0.93507064, -0.64678628],
       [ 0.49461699,  0.81585507,  0.39980029, ..., -0.13213573,
         0.29682574,  0.68622543],
       ...,
       [ 0.45138004,  1.55606023, -0.6428619 , ..., -2.14455824,
         0.29682574, -0.64678628],
       [ 0.66756478, -1.77486298,  1.44246248, ...,  0.87407553,
         0.29682574,  0.68622543],
       [ 0.25681377,  0.81585507, -0.12153081, ...,  0.87407553,
         0.29682574, -0.64678628]])

In [20]:
X_train=pd.DataFrame(preprocessor.fit_transform(X_train),columns=preprocessor.get_feature_names_out())
X_test=pd.DataFrame(preprocessor.transform(X_test),columns=preprocessor.get_feature_names_out())

In [21]:
X_train

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                 -0.975439            -0.849607            -0.121531   
1                  0.235195             1.833637            -0.121531   
2                  0.494617             0.815855             0.399800   
3                 -1.018676             0.260701             0.921131   
4                 -0.953821            -0.664555            -0.642862   
...                     ...                  ...                  ...   
135496            -1.040295            -0.016876            -0.642862   
135497             0.991842             0.168176            -0.642862   
135498             0.451380             1.556060            -0.642862   
135499             0.667565            -1.774863             1.442462   
135500             0.256814             0.815855            -0.121531   

        num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0             -1.042757        -1.080970        -1.123150           0.874076   
1              0.318447         0.279859         0.485354          -2.144558   
2              0.570855         0.606458         0.673737          -0.132136   
3             -1.214034        -1.244270        -1.195605          -0.132136   
4             -1.069801        -1.044681        -1.094168           0.874076   
...                 ...              ...              ...                ...   
135496        -1.268122        -1.244270        -1.239078           0.874076   
135497         1.048629         1.114501         1.079486           0.874076   
135498         0.516768         0.588314         0.702719          -2.144558   
135499         0.868337         0.951202         0.688228           0.874076   
135500         0.381549         0.415942         0.470863           0.874076   

        cat_pipeline__color  cat_pipeline__clarity  
0                  1.528722               1.352731  
1                 -0.935071              -0.646786  
2                  0.296826               0.686225  
3                  0.296826               0.019720  
4                  2.144670               1.352731  
...                     ...                    ...  
135496            -0.935071              -0.646786  
135497             0.296826              -1.313292  
135498             0.296826              -0.646786  
135499             0.296826               0.686225  
135500             0.296826              -0.646786  

[135501 rows x 9 columns]

In [22]:
X_test

num_pipeline__carat  num_pipeline__depth  num_pipeline__table  \
0                -0.564688            -0.942132            -0.642862   
1                -0.175556             1.000906            -0.121531   
2                -1.061913             0.260701            -0.121531   
3                 0.970223            -0.201927             1.963794   
4                -0.932202            -1.312235             0.399800   
...                    ...                  ...                  ...   
58067             1.013460             1.185958            -0.642862   
58068            -0.997058             0.260701            -1.164193   
58069            -0.197174            -3.347799             1.442462   
58070            -0.824110            -0.201927            -0.121531   
58071             2.613227            -0.757081             1.442462   

       num_pipeline__x  num_pipeline__y  num_pipeline__z  cat_pipeline__cut  \
0            -0.429765        -0.464061        -0.500036          -0.132136   
1            -0.042137        -0.028595         0.036132          -1.138347   
2            -1.304180        -1.298703        -1.268060           0.874076   
3             1.048629         0.996563         0.978049          -0.132136   
4            -1.006699        -0.990248        -1.065186          -0.132136   
...                ...              ...              ...                ...   
58067         1.003556         1.041924         1.151941          -1.138347   
58068        -1.141917        -1.126331        -1.108659           0.874076   
58069         0.102096         0.071199        -0.224706          -0.132136   
58070        -0.853450        -0.881382        -0.876803           0.874076   
58071         2.139394         2.039865         2.006912          -0.132136   

       cat_pipeline__color  cat_pipeline__clarity  
0                -0.935071               0.019720  
1                 0.912774              -0.646786  
2                 0.912774               2.685743  
3                 0.296826               0.019720  
4                -0.935071               0.686225  
...                    ...                    ...  
58067             0.912774               0.019720  
58068            -0.319122               2.019237  
58069             2.144670               0.019720  
58070             0.296826              -0.646786  
58071             2.144670               0.019720  

[58072 rows x 9 columns]

In [23]:
## Model Training
from sklearn.linear_model import LinearRegression,Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [24]:
regression = LinearRegression()
regression.fit(X_train,y_train)

LinearRegression()

In [25]:
regression.coef_

array([[ 6433.66003594,  -132.75843566,   -70.42922179, -1720.30971463,
         -499.29302619,   -63.39317848,    72.44537247,  -460.41604642,
          650.76431652]])

In [26]:
regression.intercept_

array([3970.76628955])

In [27]:
## Automate the metrics calculation
def evaluate_model(true,predict):
    mae = mean_absolute_error(true,predict)
    mse = mean_squared_error(true,predict)
    rmse = np.sqrt(mean_squared_error(true,predict))
    r2_square = r2_score(true,predict)
    return mae,rmse,r2_square

In [29]:
## Train multiple models
models = {
    'LinearRegression' : LinearRegression(),
    'Lasso' : Lasso(),
    'Ridge' : Ridge(),
    'ElasticNet' : ElasticNet()
}

model_list=[]
r2_list=[]

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train,y_train)

    #make prediction
    y_pred=model.predict(X_test)

    mae,rmse,r2_square=evaluate_model(y_test,y_pred)
    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print("model Training Performance")
    print("RMSE: ",rmse)
    print("MAE:",mae)
    print("R2 Score:",r2_square*100)

    r2_list.append(r2_square)

    print('='*35)
    print('\n')

LinearRegression
model Training Performance
RMSE:  1013.9047094344005
MAE: 674.0255115796832
R2 Score: 93.68908248567512


Lasso
model Training Performance
RMSE:  1013.8784226767013
MAE: 675.0716923362161
R2 Score: 93.68940971841704


Ridge
model Training Performance
RMSE:  1013.9059272771568
MAE: 674.0555800798383
R2 Score: 93.68906732505947


ElasticNet
model Training Performance
RMSE:  1533.4162456064048
MAE: 1060.7368759154729
R2 Score: 85.56494831165182




In [30]:
model_list

['LinearRegression', 'Lasso', 'Ridge', 'ElasticNet']